version: "3.9"
services:
  build-quarto:
    init: true
    image: w4bo/quarto-slides:1.0.23
    hostname: build-quarto
    container_name: build-quarto
    ports:
      - "6778:6778"
    volumes:
      - ./:/data
    command: ["/bin/bash", "/data/build.sh"]

  jupyter:
    hostname: jupyter
    container_name: jupyter
    init: true
    build: .
    ports:
      - 8888:8888
    volumes:
      - .:/notebooks