services:
  build-quarto:
    init: true
    image: w4bo/quarto-slides:1.0.24
    hostname: build-quarto
    container_name: build-quarto
    volumes:
      - ./:/data
    command: ["/bin/bash", "/data/build.sh"]