version: "3.9"
services:
  build-quarto:
    init: true
    # restart: always
    image: w4bo/quarto-slides:1.0.23
    hostname: build-quarto
    container_name: build-quarto
    ports:
      - "6778:6778"
    volumes:
      - ./:/data
    command: ["/bin/bash", "/data/build.sh"]